#:kivy 2.0.0

WidgetsExample:

<WidgetsExample>:
    cols: 3
    Button:
        text: 'Click here'
        on_press: root.onCount()
        font_name: "../fonts/SoleilBook.otf"
    Label:
        text: root.text
        font_name: "../fonts/SoleilBook.otf"
        font_size: 21
    ToggleButton:
        text: 'Off'
        on_state: root.onToggle(self)
        font_name: "../fonts/Odachi.otf"
        font_size: 45
        size_hint_x: None
        width: "100dp"
