Player:

<Player>:
    source: 'resources/videos/01_fakie_gazelle.webm'
    state: 'play'
    allow_strech: True

<MainWindow>:
    orientation: 'vertical'
    BoxLayout:
        size_hint_y: None
        height: '65dp'
        Label:
            text: 'Logo'
        Button:
            text: 'Menu'
    VideoSelection:
    Label:
        text: 'copyright - 2022, Maxime Wattez'

    VideoPlayer:
        source: root.video_path


<VideoSelection>:
